local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency:  1.0   # 10.0  
  publish_frequency: 1.0   # 2.0 
  
  static_map:     false
  rolling_window: true
  width:          2.0     # 5.0
  height:         2.0     # 5.0
  resolution:     0.05    # 0.1
