local_costmap:
  global_frame:           /Pioneer3AT/odom
  update_frequency:       2.0   # 10.0  
  publish_frequency:      2.0   # 2.0 
  
  
 ### Map management parameters ### 
  static_map:             false  
  rolling_window:         true
  unknown_cost_value:     0
  publish_voxel_map:      false
  lethal_cost_threshold:  100
  map_topic:              /Pioneer3AT/map

  # The following parameters are overwritten if "static_map" is set to true:
  width:                  3.0     # 5.0
  height:                 3.0     # 5.0
  resolution:             0.02    # 0.1
  origin_x:               0.0
  origin_y:               0.0

  ### Map type parameters ###
  map_type:               costmap

  # The following parameters are only used if map_type is set to "costmap":
  track_unknown_space:    false
  
  # The following parameters are only used if map_type is set to "voxel":
  #origin_z:              0.0
  #z_resolution:          0.2
  #z_voxels:              10
  #unknown_threshold:     10
  #mark_threshold:        0

  
  
  
  
