
base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS

recovery_behaviors: [{
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery1,
    type: rotate_recovery/RotateRecovery
  }, {
    name: aggressive_reset,
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery2,
    type: rotate_recovery/RotateRecovery
  }]
  
planner_frequency:          0     # Global plan updates on new goal or path blocked only
controller_frequency:       20
planner_patience:           5.0
controller_patience:        3.0
conservative_reset_dist:    2.0
recovery_behavior_enabled:  true
clearing_rotation_allowed:  true
shutdown_costmaps:          false
oscillation_timeout:        0.0
oscillation_distance:       0.5




# http://www.ros.org/wiki/navfn
NavfnROS:
  allow_unknown:                      true
  planner_window_x:                   0.0
  planner_window_y:                   0.0
  default_tolerance:                  0.1
  visualize_potential:                true
  planner_costmap_publish_frequency:  0.5
  
  

# http://www.ros.org/wiki/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x:                    10.0
  acc_lim_y:                    0.0
  acc_lim_th:                   3.5
  max_vel_x:                    0.8
  min_vel_x:                    0.05
  max_rotational_vel:           0.5
  min_in_place_rotational_vel:  0.05
  escape_vel:                   -0.2
  holonomic_robot:              false
  
# The following parameters are only used if holonomic_robot is set to true:
  y_vels: [-0.3, -0.1, 0.1, 0.3]
  
# Goal Tolerance Parameters
  yaw_goal_tolerance:           0.10
  xy_goal_tolerance:            0.10
  latch_xy_goal_tolerance:      true
  
# Forward Simulation Parameters
  sim_time:                     4.0
  sim_granularity:              0.25
  angular_sim_granularity:      0.05
  vx_samples:                   20
  vtheta_samples:               40
  # controller_frequency:       20 # set above
  
# Trajectory Scoring Parameters
  meter_scoring:                true
  path_distance_bias:           0.5
  goal_distance_bias:           2.5
  occdist_scale:                0.1
  heading_lookahead:            0.325
  heading_scoring:              true
  heading_scoring_timestep:     0.8
  dwa:                          true
  publish_cost_grid_pc:         false
  global_frame_id:              /Pioneer3AT/odom
  
# Oscillation Prevention Parameters
  oscillation_reset_dist:       0.1
  
# Global Plan Parameters
  prune_plan:                   true
  
  
### Map management parameters ###
# Located in costmap_global.yaml & _local.yaml
  
  
